services:
  strapi:
    image: node:18
    container_name: strapi-dev
    working_dir: /app
    volumes:
      - ./:/app
    command: npm run develop
    environment:
      NODE_ENV: development
    ports:
      - "1337:1337"

  postgres:
    image: postgres:16
    container_name: strapi-postgres-dev
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapipassword
